### PR TITLE
manual: Add tutorial on how to use nixos-install with Colmena

### PR DESCRIPTION
**Pull request by itslychee**

### CODE REVIEW

**Review by mrshmllow — APPROVED** [review]

**Comment by acid-bong** [comment]
Is it a good idea to use a live ISO as an intermediate? What if the closure is larger that the RAM amount (like in my case: 4GB of RAM and the system closure is around 12GB)?

**Comment by itslychee** [comment]
yea that's the only caveat of this, though I believe you can use `colmena build -f flake-uri` to build closures on a remote repository, but you're still going to get the same problem I believe, but I also think the same could be said for an ordinary `nixos-install --flake ...` invocation? not sure!

**Comment by TornaxO7** [comment]
May I ask why this got closed?

**Comment by IogaMaster** [comment]
I can reopen it!

**Pull request closed without merging**
