### PR TITLE
streaming evaluator: respect eval-nodes-limit

### PR DESCRIPTION
**Pull request by lheckemann**
I'm not sure if use of a public field is the most elegant way to implement this, but I thought I'd throw this over the fence as a minimal working implementation :)

### CODE REVIEW

**Comment by zhaofengli** [comment]
Sorry for the delay. I modified the code a little bit and it should be good to go.

I hadn't looked at the streaming evaluator lately, but now with [the latest changes](https://github.com/nix-community/nix-eval-jobs/pull/36) (patched downstream [here](https://github.com/zhaofengli/colmena/commit/09a8a72b0c5113aa40648949986278040487c9bd)) it should actually be "streaming."

**Comment by Mic92** [comment]
Cool. Did not know that this was already adopted. Can I link your projects in my README?

**Comment by zhaofengli** [comment]
@Mic92 Sure thing! Currently this is gated behind `--evaluator streaming` in Colmena. nix-eval-jobs is also used in Robotnix for [its CI](https://github.com/danielfullmer/robotnix/blob/38b80700ee4265c306dcfdcce45056e32ab2973f/.github/workflows/instantiate.yml#L18).

**Comment by Mic92** [comment]
Added both.

**Pull request merged**
