### PR TITLE
resolve symlinks in temporary directories, when used with nix

### LINKED ISSUE #190: error: path '«unknown»/tmp' is a symlink on Darwin
A `colmena build` with flakes will choke on Darwin, because `/tmp` is a symlink to `/private/tmp`.

I've created a [minimal flake example here](https://github.com/camelpunch/colmena-repro).

The following reproduces the error:

```
nix develop --command -- colmena build
```

### PR DESCRIPTION
**Pull request by Mic92**
darwin puts them there and symlinks are not allowed in flakes anymore.

fixes #190

### CODE REVIEW

**Comment by Mic92** [comment]
Also pulled in as a patch in https://github.com/NixOS/nixpkgs/pull/353776

**Comment by SuperSandro2000** [comment]
rustfmt is unhappy and some test is failing

**Comment by zhaofengli** [comment]
> rustfmt is unhappy and some test is failing

I'll take care of rustfmt and CI. We probably need an integration test on macOS so this doesn't break again.

I think I prefer the #233 since creating the files themselves shouldn't need canonicalization.

**Comment by zhaofengli** [comment]
Thanks for the PR, but I would like to take #233 instead.

**Pull request closed without merging**
